<?php

return [
    'version'               => '1.0.1',
    'categories'            => json_decode(env('GAME_SLOTS_3D_CATEGORIES', json_encode(['Slots']))),
    'banner'                => env('GAME_SLOTS_3D_BANNER', '/images/games/slots-3d.jpg'),
    'texture'               => env('GAME_SLOTS_3D_TEXTURE', '/images/games/slots-3d/texture.png',),
    'table_show'            => env('GAME_SLOTS_3D_TABLE_SHOW', 1),
    'table_color'           => env('GAME_SLOTS_3D_TABLE_COLOR', '#252525'),
    'table_border_color'    => env('GAME_SLOTS_3D_TABLE_BORDER_COLOR', '#555555'),
    'table_texture'         => env('GAME_SLOTS_3D_TABLE_TEXTURE', '/images/games/slots-3d/table-texture.jpg'),
//     'reflection'         => env('GAME_SLOTS_3D_BACKGROUND', '/images/games/slots-3d/background-skybox.jpg'),
//    'background_env'        => env('GAME_SLOTS_3D_BACKGROUND_ENV', '/images/games/slots-3d/background.jpg'),
    'background_skybox'     => env('GAME_SLOTS_3D_BACKGROUND_SKYBOX', '/images/games/slots-3d/background-skybox.jpg'),
    'background_skybox_rotate' => env('GAME_SLOTS_3D_BACKGROUND_SKYBOX_ROTATE', 0),
    'background_skybox_deep'  => env('GAME_SLOTS_3D_BACKGROUND_SKYBOX_DEEP', 2000),
    'camera_position'       => json_decode(env('GAME_SLOTS_3D_CAMERA_POSITION', '[500, 357, 1200]')),
    'camera_fov'            => env('GAME_SLOTS_3D_CAMERA_FOV', 45),
    'min_bet'               => env('GAME_SLOTS_3D_MIN_BET', 1),
    'max_bet'               => env('GAME_SLOTS_3D_MAX_BET', 50),
    'bet_change_amount'     => env('GAME_SLOTS_3D_BET_CHANGE_AMOUNT', 1),
    'default_bet_amount'    => env('GAME_SLOTS_3D_DEFAULT_BET_AMOUNT', 1),
    'symbols'               => json_decode(env('GAME_SLOTS_3D_SYMBOLS', json_encode([
        '/images/games/slots-3d/apple.png',
        '/images/games/slots-3d/bar.png',
        '/images/games/slots-3d/bell.png',
        '/images/games/slots-3d/cherry.png',
        '/images/games/slots-3d/lemon.png',
        '/images/games/slots-3d/orange.png',
        '/images/games/slots-3d/plum.png',
        '/images/games/slots-3d/seven.png',
        '/images/games/slots-3d/water-melon.png',
    ]))),
    'reels' => json_decode(env('GAME_SLOTS_3D_REELS', json_encode([
        [0,1,2,3,4,5,6,7,8],
        [1,2,3,4,5,6,7,8,0],
        [2,3,4,5,6,7,8,0,1],
    ]))),
    'paytable' => json_decode(env('GAME_SLOTS_3D_PAYTABLE', json_encode([
        ['positions' => [0,0,0], 'payout' => 3],
        ['positions' => [0,0,NULL], 'payout' => 2],
        ['positions' => [1,1,1], 'payout' => 5],
        ['positions' => [2,2,2], 'payout' => 10],
        ['positions' => [3,3,3], 'payout' => 25],
        ['positions' => [4,4,4], 'payout' => 2],
        ['positions' => [5,5,5], 'payout' => 2],
        ['positions' => [6,6,6], 'payout' => 2],
        ['positions' => [7,7,7], 'payout' => 50],
        ['positions' => [8,8,8], 'payout' => 3],
    ]))),
];
